<?xml version="1.0"?>
<package format="3">
  <name>vector_imu</name>
  <version>0.1.0</version>
  <description>LSM6DSV16X IMU on the CM5 carrier and MMC5983MA compass on the nose board: imu and mag</description>
  <maintainer email="avladescu2000@gmail.com">Andrei Vladescu</maintainer>
  <license>TBD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
