#ifndef BOARD_PINS_H
#define BOARD_PINS_H

/* IO MCU on the CM5 carrier (U30, STM32C092KCT6, LQFP32), sheet io_mcu.kicad_sch */

/* USART1 to the CM5 (GPIO5 / GPIO4), also ST's ROM bootloader */
#define HOST_PORT GPIOA
#define HOST_PINS (GPIO_PIN_9 | GPIO_PIN_10)
#define HOST_AF GPIO_AF1_USART1
/* USART2 to the ELRS receiver */
#define ELRS_PORT GPIOA
#define ELRS_PINS (GPIO_PIN_2 | GPIO_PIN_3)
#define ELRS_AF GPIO_AF1_USART2
/* USART4 RX from the LD19 (TX unused) */
#define LIDAR_PORT GPIOA
#define LIDAR_PIN GPIO_PIN_1
#define LIDAR_AF GPIO_AF9_USART4
/* USART3 to the MAX-M10S: TX PB8 (AF0), RX PB9 (AF4) */
#define GNSS_PORT GPIOB
#define GNSS_TX_PIN GPIO_PIN_8
#define GNSS_TX_AF GPIO_AF0_USART3
#define GNSS_RX_PIN GPIO_PIN_9
#define GNSS_RX_AF GPIO_AF4_USART3
#define GNSS_PPS_PORT GPIOC
#define GNSS_PPS_PIN GPIO_PIN_14

/* TIM3_CH4 lidar speed PWM, TIM14_CH1 buzzer (MMBT3904 low side) */
#define LIDAR_PWM_PORT GPIOB
#define LIDAR_PWM_PIN GPIO_PIN_1
#define LIDAR_PWM_AF GPIO_AF1_TIM3
#define BUZZER_PORT GPIOA
#define BUZZER_PIN GPIO_PIN_4
#define BUZZER_AF GPIO_AF4_TIM14

/* RFM95W on SPI1 (AF0): SCK PB3, MISO PB4, MOSI PB5; NSS PA15, NRST PA12, DIO0 PA11, DIO1 PC6 */
#define LORA_SPI_PORT GPIOB
#define LORA_SPI_PINS (GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5)
#define LORA_NSS_PORT GPIOA
#define LORA_NSS_PIN GPIO_PIN_15
#define LORA_NRST_PORT GPIOA
#define LORA_NRST_PIN GPIO_PIN_12
#define LORA_DIO0_PORT GPIOA
#define LORA_DIO0_PIN GPIO_PIN_11
#define LORA_DIO1_PORT GPIOC
#define LORA_DIO1_PIN GPIO_PIN_6

/* ADC: VBAT (100k / 22k) IN0, 5 V (10k / 10k) IN6, NTC IN7 */
#define ADC_PORT GPIOA
#define ADC_PINS (GPIO_PIN_0 | GPIO_PIN_6 | GPIO_PIN_7)
#define ADC_CH_VBAT 0
#define ADC_CH_5V 6
#define ADC_CH_NTC 7
#define ADC_CH_VREFINT 10

/* LTE supply: TPS62933 EN (100k pull-down), STATUS through the TXS0104 */
#define LTE_EN_PORT GPIOB
#define LTE_EN_PIN GPIO_PIN_0
#define LTE_STATUS_PORT GPIOB
#define LTE_STATUS_PIN GPIO_PIN_2

#define LED_PORT GPIOC
#define LED_PIN GPIO_PIN_15

#endif
