"""View the full Fusion 360 model (vector_cad.urdf.xacro) in rviz, with sliders for the joints.

  ros2 launch vector_bringup view_cad.launch.py

vector_cad.urdf.xacro is generated by software/tools/cad_urdf.py from the raw Fusion export
(vector_cad_raw.urdf.xacro): same joint names, signs, zeros and limits as vector.urdf.xacro, so
the sliders move the joints the way the gait does.
"""
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.substitutions import Command
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue


def generate_launch_description():
    desc = get_package_share_directory('vector_description')
    bringup = get_package_share_directory('vector_bringup')

    robot_description = ParameterValue(
        Command(['xacro ', os.path.join(desc, 'urdf', 'vector_cad.urdf.xacro')]),
        value_type=str)

    return LaunchDescription([
        Node(
            package='robot_state_publisher',
            executable='robot_state_publisher',
            parameters=[{'robot_description': robot_description}]),

        Node(
            package='joint_state_publisher_gui',
            executable='joint_state_publisher_gui'),

        Node(
            package='rviz2',
            executable='rviz2',
            arguments=['-d', os.path.join(bringup, 'rviz', 'cad.rviz')]),
    ])
